### PR TITLE
Fix error handling and logging in DcodeKiApp

### PR DESCRIPTION
**Pull request by ayushmorbar**
## Current behavior
- Previously, the application did not handle exceptions and errors effectively. This led to crashes and uninformative error messages when unexpected situations occurred, such as a file not being found or an error occurring during the build, start, or screen transition processes.

## Proposed changes
- This pull request improves error handling in the application by adding try/except blocks around critical sections of code. These blocks catch exceptions, log them using the logging module, display an informative error message to the user via self.ids.string.text, and then re-raise the exception. This approach provides more robustness and better user feedback.

## Checks
- To verify the changes, run the application and induce some errors (like removing a necessary file or causing an exception in the code). Check the log to ensure that the errors are being logged correctly, and observe the application's interface to confirm that appropriate error messages are displayed to the user.

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by Pankaj0038** [comment]
@ayushmorbar you didn't consider the encoding functions which we are using , like if anybody send any string as a key to xor encode the algorithm will break 

so add try except to the switch cases also, like 
```
			case "text2XOR2text":
				try:
					decoded = text2XOR2text.encode(cipher,cipher_key)
				except Exception as e:
					decoded= e
```

**Comment by ayushmorbar** [comment]
oh right, lemme fix that.

**Comment by Pankaj0038** [comment]
well done @ayushmorbar

**Comment by Pankaj0038** [comment]
@ayushmorbar you did it very well , thus enhancing the issue level to medium

**Comment by ayushmorbar** [comment]
thank you @Pankaj0038 , i appreciate it 🙌

**Pull request merged**
