### PR TITLE
new pr

### PR DESCRIPTION
**Pull request by daksh1210jain**

### CODE REVIEW

**Comment by daksh1210jain** [comment]
sir please have a look and tell what to do anything else

**Comment by Pankaj0038** [comment]
describe about the screenshot like mention which feature it is indicating 

ex: search functionality , Copy function , several decoder , Gui etc

**Comment by daksh1210jain** [comment]
sir now kindly have a look

**Comment by Pankaj0038** [comment]
Bro merging your pr but it doesn't look attractive at all ,

**Pull request merged**
