### PR TITLE
url_encoding_decoding added

### PR DESCRIPTION
**Pull request by pranjalipilankar**

### CODE REVIEW

**Comment by pranjalipilankar** [comment]
url_encoding_decoding

**Comment by Pankaj0038** [comment]
don't just use library function , write algorithm

**Comment by pranjalipilankar** [comment]
I have written an algorithm but it does not work correctly with £, 円 and similar unusual symbols.

**Comment by Pankaj0038** [comment]
okay send the other algorithm ,

**Comment by pranjalipilankar** [comment]
#!/usr/bin/env python3

def encode(plaintext):
    ciphertext = ""
    for char in plaintext:
        if char.isalnum() or char in ['-', '_', '.', '~']:
            ciphertext += char
        else:
            ciphertext += '%' + '{:02X}'.format(ord(char))
    return ciphertext

def decode(ciphertext):
    plaintext = ""
    i = 0
    while i < len(ciphertext):
        if ciphertext[i] == '%' and i + 2 < len(ciphertext):
            hex_chars = ciphertext[i + 1:i + 3]
            try:
                plaintext += chr(int(hex_chars, 16))
                i += 3
            except ValueError:
                plaintext += ciphertext[i]
                i += 1
        else:
            plaintext += ciphertext[i]
            i += 1
    return plaintext

def main():
    text = input("Enter the text to be encoded/decoded: ")
    option = input("Encode/Decode? (e/d): ")

    if option == "e":
        ciphertext = encode(text)
        print(ciphertext)
    elif option == "d":
        plaintext = decode(text)
        print(plaintext)
    else:
        print("Invalid option!")


if __name__ == "__main__":
    main()

**Pull request closed without merging**
