### PR TITLE
Adding base45 and base62 

### PR DESCRIPTION
**Pull request by yashasvini121**
Resolving issue #45 
Adding the encoder and decoder functions for Base45 and Base62

### CODE REVIEW

**Comment by Pankaj0038** [comment]
don't use bytes as a return type , just work with strings

**Comment by Pankaj0038** [comment]
By the way , did you use any AI tool to generate the code ?

**Comment by yashasvini121** [comment]
No, I used the code from the base45 python module, and a golang based program code for the base62 task. I hope that doesn't disqualify my code.
The fxns return string, I had not updated the return type annotations, my bad

**Comment by Pankaj0038** [comment]
okay can you send those python and golang code , I'm not disqualifying this but have a bit doubt 
Actually your code is too much professional for beginner friendly open source contest

**Comment by yashasvini121** [comment]
Ok, https://github.com/kirei/python-base45 and https://medium.com/@anabhishek.jha/base-62-text-encoding-decoding-b43921c7a954

**Comment by Pankaj0038** [comment]
I think you send wrong link ! , base45 code is not even initialized in that code , just used library function to encode or decode

**Comment by yashasvini121** [comment]
no it is, in the `__init__` file, https://github.com/kirei/python-base45/blob/main/base45/__init__.py

**Comment by Pankaj0038** [comment]
you need to change the code at least , 
you can use another's algorithm but cannot submit as it is , sorry cannot merge this pr if you need more time then take your time but don't just submit like this
Or if you have any doubt about the algorithm then you can also ask us (mentors) for this 
Sorry for the rejection , hoping better outcome from you

**Comment by yashasvini121** [comment]
Ok, no problem, I will change the code.

**Comment by yashasvini121** [comment]
Hi @Pankaj0038 , could you please review my pr and tell me if any improvements are required.

**Comment by Pankaj0038** [comment]
that's fine , well done @yashasvini121

**Pull request merged**
