### PR TITLE
added changes

### PR DESCRIPTION
**Pull request by daksh1210jain**

### CODE REVIEW

**Comment by daksh1210jain** [comment]
sir kindly have a look i have made some changes kindly review it

**Comment by Pankaj0038** [comment]
@daksh1210jain  you missed the scroll bar for the buttons 

(scroll view for the grid layout)
Screenshot_2024-01-23_19_51_05

**Comment by Pankaj0038** [comment]
but overall this is really awesome love it man @daksh1210jain , just add the scroll bar

**Comment by daksh1210jain** [comment]
sir i edited the code but scroll bar is not coming . please have a look i added the code snippet

**Pull request merged**
