### PR TITLE
added the changes

### PR DESCRIPTION
**Pull request by daksh1210jain**

### CODE REVIEW

**Comment by daksh1210jain** [comment]
sir please have a look

**Comment by Pankaj0038** [comment]
Okay that's good , just make it self executable

I mean
if __name__== "__main__":
 Then take input and choice print the corresponding message

**Comment by daksh1210jain** [comment]
sir can you explain more clearly exactly what do you want to add

**Comment by Pankaj0038** [comment]
Screenshot_2024-01-21_15_13_48

I'm taking about this portion of code , which makes it run its functionality

**Comment by daksh1210jain** [comment]
so you expect in the above portion of the code i take input for upper lower and reverse right?

**Comment by Pankaj0038** [comment]
you just add this in the extra.py file for all of the operations

**Comment by daksh1210jain** [comment]
sir it is generating error

**Comment by Pankaj0038** [comment]
check your local repo , I changed your code 
you can ask me if there is any doubt

**Comment by Pankaj0038** [comment]
okay @daksh1210jain dm me in discord I'm explaining you why we add that portion of code

**Pull request merged**
