### PR TITLE
feat: Add URL encoding and decoding functionality

### PR DESCRIPTION
**Pull request by ayushmorbar**
## Current behavior
Previously, our application did not have the ability to encode and decode URLs.

## Proposed changes
- This pull request introduces two new functions, encode() and decode(), to our url.py file. The encode() function takes a plaintext string and encodes it into a URL safe format. The decode() function takes a URL encoded string and decodes it back into plaintext. These functions will allow our application to handle URL encoding and decoding, which is essential for safe and effective web communication.
- This pull request also added action buttons and button in the dcodeKi.kv for URL encoding and decoding.

## Checks
- Ensured compatibility with existing file types.
- The encode() and decode() functions have been tested.
- The Action Button & Button for URL encoding and decoding have been tested.
- The code follows the project's coding style guidelines.

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by ayushmorbar** [comment]
Do not merge the Leet Speak (1337) commit, though the code is complete I mistakenly added to this pr.

**Comment by ayushmorbar** [comment]
#48

**Comment by Pankaj0038** [comment]
@ayushmorbar is this an AI generated code ?

**Comment by ayushmorbar** [comment]
No, not really i manually coded except the documentation & comment part which is AI generated. I've taken reference to understand from the other code present within the same directory of this project and then with some research and learning about the issue thoroughly, I did code.

**Comment by Pankaj0038** [comment]
okay

**Pull request merged**
