### PR TITLE
feat: Add LEET Speak (aka 1337) encoding and decoding functionality

### PR DESCRIPTION
**Pull request by ayushmorbar**
## Current behavior
- Previously, our application lacked LEET Speak (or 1337) encoding and decoding capabilities, hindering effective communication.

## Proposed changes
- Introduces two new functions, encode() and decode(), to encoders/leet.py. The encode() function transforms a plaintext string into a LEET Speak format, while decode() reverses the process. These additions enable our application to handle essential encoding and decoding for secure communication.
- Adds action buttons and a button in dcodeKi.kv for convenient encoding and decoding.

## Checks
- Ensures compatibility with existing file types. 
- The encode() and decode() functions have undergone thorough testing. 
- The Action Button & Button for encoding and decoding have been rigorously tested.
- The code adheres to the project's coding style guidelines.

## Refer Issue #44

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by Pankaj0038** [comment]
Remove the unnecessary dictionary element

**Comment by ayushmorbar** [comment]
Regarding this, I'm bit confused since the below given are the encoded leet speak in key-value pairs, so shall I take care these as well, while removing the unnecessary elements in `leet.py`. Can you provide me a with a better reference? 


```
leet = {
    'A': '4',
    'B': '8',
    'C': '(',
    'D': '|)',
    'E': '3',
    'F': '|=',
    'G': '9',
    'H': '#',
    'I': '1',
    'J': '_|',
    'K': '|<',
    'L': '|',
    'M': '/\\/\\',
    'N': '/\\/',
    'O': '0',
    'P': '|*',
    'Q': '(,)',
    'R': '|2',
    'S': '5',
    'T': '7',
    'U': '|_| or \\_/',
    'V': '\\/',
    'W': '\\/\\/',
    'X': '><',
    'Y': '`/`',
    'Z': '2'
}
```

**Comment by Pankaj0038** [comment]
A	4 /\ @ /-\ |-\
B	8 |3 13 ß
C	( ¢ < [ ©
D	[) |> |) |]
E	3 € є [-
F	|= ƒ /=
G	6 (_+
H	# /-/ [-] ]-[ )-( (-) :-: |~| |-| ]~[ }{
I	1 ! | ][ ] :
J	_| _/ ¿ (/ ʝ ;
K	X |< |{ ɮ
L	£ 1_ ℓ |_ [_
M	|V| |\/| /\/\ /V\
N	|V |\| /\/ [\] /V
O	[] 0 () °
P	|* |o |º |° /*
Q	¶ (_,) ()_ 0_ °| <| 0,
R	2 |? /2 ® Я |2
S	5 $ § _/¯
T	7 † ¯|¯
U	(_) |_| L| µ
V	\/ |/
W	\/\/ vv \//' \^/ \V/ \|/ \_|_/ \_:_/
X	>< }{ × )(
Y	`/ φ ¥ \/
Z	≥' 7_ >_



If you want to consider all the values then add all this values for decoding , but for encoding use the numbers only to replace the characters

**Comment by Pankaj0038** [comment]
but its okay to make it simple like using a = 4 , b= 8 , e=3, g=9 or G=6 , L = 1 , o = 0 , s = 5 , t = 7 , z = 2 only

**Comment by ayushmorbar** [comment]
> but its okay to make it simple like using a = 4 , b= 8 , e=3, g=9 or G=6 , L = 1 , o = 0 , s = 5 , t = 7 , z = 2 only

I've made the changes.

**Pull request merged**
